blank_issues_enabled: true
contact_links:
  - name: No GitHub account? Not sure how to use GitHub?
    url: https://docs.qq.com/form/page/DSlFOZmpTQ1JsZ2FD
    about: Click here to submit a bug report using Tencent Docs